## PG

development:
  adapter: postgresql
  database: woodenhorse_development
  pool: 5
  username: samjeston
  password:

test:
  adapter: postgresql
  database: woodenhorse_test
  pool: 5
  username: samjeston
  password:

production:
  adapter: postgresql
  database: woodenhorse_production
  pool: 5
  username: THEWOODENHORSERESTAURANT
  password: <%= ENV['THEWOODENHORSERESTAURANT_DATABASE_PASSWORD'] %>
